-- Run this if the table already exists:
alter table samples add column annotations jsonb;

-- Or if you are starting fresh:
-- create table samples (
--   id bigint generated by default as identity primary key,
--   part text not null,
--   topic text not null,
--   question text not null,
--   answer text not null,
--   annotations jsonb,
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null
-- );
